version: '3.8'

services:
  components-registry-service:
    container_name: components-registry-service-automation-test
    image: ${DOCKER_REGISTRY}/octopusden/components-registry-service:${COMPONENTS_REGISTRY_SERVICE_VERSION}
    environment:
      - SPRING_CONFIG_ADDITIONAL_LOCATION=/
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_CLOUD_CONFIG_ENABLED=false
    volumes:
      - ./components-registry-service.yaml:/application-test.yaml
      - ./components-registry:/components-registry
    ports:
      - "4567:4567"
